import { ViewTransition } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";
import Link from "next/link";
import { createClient } from "@/prismicio";
import { PrismicNextLink } from "@prismicio/next";

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransition>
      <html lang="en">
        <body
          className={`${geist.variable} ${geistMono.variable} antialiased min-h-svh flex flex-col`}
        >
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </body>
        <PrismicPreview repositoryName={repositoryName} />
      </html>
    </ViewTransition>
  );
}

async function Header() {
  const client = createClient();
  const settings = await client.getSingle("settings");

  return (
    <header>
      <div className="max-w-4xl w-full mx-auto px-5 py-5 flex items-center justify-between">
        <Link
          href="/"
          className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
        >
          Index
        </Link>

        {settings.data.navigation.length > 0 && (
          <nav className="flex gap-4 items-center justify-end">
            {settings.data.navigation.map((item, index) => (
              <PrismicNextLink
                key={index}
                field={item.link}
                className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
              >
                {item.link.text}
              </PrismicNextLink>
            ))}
          </nav>
        )}
      </div>
    </header>
  );
}

async function Footer() {
  const client = createClient();
  const settings = await client.getSingle("settings");

  return (
    <footer className="relative pt-5 pb-8">
      <div className="max-w-4xl w-full mx-auto px-5">
        <hr className="opacity-10 text-foreground" />
        <div className="flex items-center justify-between pt-5">
          <p className="text-foreground text-xs">
            Built by{" "}
            <Link
              href="https://github.com/LucasJacobGill"
              className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear"
            >
              Lucas Gill
            </Link>
          </p>

          {settings.data.navigation.length > 0 && (
            <nav className="flex gap-4 items-center justify-end">
              <Link
                href="/"
                className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
              >
                Index
              </Link>
              {settings.data.navigation.map((item, index) => (
                <PrismicNextLink
                  key={index}
                  field={item.link}
                  className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
                >
                  {item.link.text}
                </PrismicNextLink>
              ))}
            </nav>
          )}
        </div>
      </div>
    </footer>
  );
}
