import { ViewTransition } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrismicPreview } from "@prismicio/next";
import { repositoryName } from "@/prismicio";
import Link from "next/link";
import { createClient } from "@/prismicio";
import { PrismicNextLink } from "@prismicio/next";
import * as Dialog from "@radix-ui/react-dialog";
import { Menu, X } from "lucide-react";
import { cn } from "@/lib/utils";

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransition>
      <html lang="en">
        <body
          className={`${geist.variable} ${geistMono.variable} antialiased min-h-svh flex flex-col`}
        >
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </body>
        <PrismicPreview repositoryName={repositoryName} />
      </html>
    </ViewTransition>
  );
}

async function Header() {
  const client = createClient();
  const settings = await client.getSingle("settings");

  return (
    <header>
      <div className="max-w-4xl w-full mx-auto px-5 py-5 flex items-center justify-between">
        <Link
          href="/"
          className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
        >
          Index
        </Link>

        {settings.data.navigation.length > 0 && (
          <nav className="hidden md:flex gap-4 items-center justify-end">
            {settings.data.navigation.map((item, index) => (
              <PrismicNextLink
                key={index}
                field={item.link}
                className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
              >
                {item.link.text}
              </PrismicNextLink>
            ))}
          </nav>
        )}

        <div className="md:hidden">
          <MobileNav />
        </div>
      </div>
    </header>
  );
}

async function MobileNav() {
  const client = createClient();
  const settings = await client.getSingle("settings");

  return (
    <Dialog.Root>
      <Dialog.Trigger
        className={cn(
          "xl:hidden",
          "data-[state='open']:[&>svg:nth-child(1)]:hidden data-[state='closed']:[&>svg:nth-child(2)]:hidden"
        )}
      >
        <Menu className="stroke-foreground" size={16} />
        <X className="stroke-foreground" size={16} />
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Content
          aria-describedby={undefined}
          className="fixed inset-0 top-16 z-50 h-svh w-full overflow-y-scroll bg-background xl:invisible xl:hidden data-[state='open']:animate-slide-from-right data-[state='closed']:animate-slide-to-right"
        >
          <span className="sr-only">
            <Dialog.Title>Mobile Navigation</Dialog.Title>
          </span>
          <nav>
            <ul className="flex flex-col gap-4 p-5 bg-background/95 backdrop-blur-md rounded-md shadow-lg border border-foreground/10">
              {settings.data.navigation.map((item, index) => (
                <li key={index}>
                  <PrismicNextLink
                    field={item.link}
                    className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
                  >
                    {item.link.text}
                  </PrismicNextLink>
                </li>
              ))}
            </ul>
          </nav>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

async function Footer() {
  const client = createClient();
  const settings = await client.getSingle("settings");

  return (
    <footer className="relative pt-5 pb-8">
      <div className="max-w-4xl w-full mx-auto px-5">
        <hr className="opacity-10 text-foreground" />
        <div className="flex items-center justify-between pt-5">
          <p className="text-foreground text-xs">
            Built by{" "}
            <Link
              href="https://github.com/LucasJacobGill"
              className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear"
            >
              Lucas Gill
            </Link>
          </p>

          {settings.data.navigation.length > 0 && (
            <nav className="flex gap-4 items-center justify-end">
              <Link
                href="/"
                className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
              >
                Index
              </Link>
              {settings.data.navigation.map((item, index) => (
                <PrismicNextLink
                  key={index}
                  field={item.link}
                  className="text-foreground underline underline-offset-4 decoration-transparent hover:decoration-current hover:opacity-75 transition-colors duration-200 ease-linear text-xs"
                >
                  {item.link.text}
                </PrismicNextLink>
              ))}
            </nav>
          )}
        </div>
      </div>
    </footer>
  );
}
