// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_posts: dynamic(() => import("./BlogPosts")),
  rich_text: dynamic(() => import("./RichText")),
};
